-- 1. Upgrade 'works' table
alter table public.works add column if not exists tags text[] default '{}';
alter table public.works add column if not exists featured boolean default false;
alter table public.works add column if not exists status text default 'published'; -- draft, published, archived
alter table public.works add column if not exists views integer default 0;

-- 2. Create 'portal_items' table
create table if not exists public.portal_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  label text not null,
  url text not null,
  description text,
  icon text not null, -- Phosphor icon name e.g. "ph-github-logo"
  category text default 'SOCIAL', -- SOCIAL, PROJECT, RESOURCE
  is_visible boolean default true,
  sort_order integer default 0
);

-- 3. Create 'profile' table
create table if not exists public.profile (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text default 'Luki',
  bio text,
  avatar_url text,
  status text default 'Online',
  socials jsonb default '{}'::jsonb, -- Store extra links or metadata
  location text,
  email text
);

-- Ensure only one profile row exists (optional constraint, or just manage via ID=1)
-- For simplicity, we will just insert a default row if empty
insert into public.profile (id, full_name, bio, status)
select 1, 'Luki', 'Welcome to the void.', 'Online'
where not exists (select 1 from public.profile);

-- 4. Create 'playlist' table
create table if not exists public.playlist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  youtube_id text not null,
  title text not null,
  artist text not null,
  sort_order integer default 0,
  lyrics_content text -- JSON string or raw text for timed lyrics
);

-- 5. Enable RLS
alter table public.portal_items enable row level security;
alter table public.profile enable row level security;
alter table public.playlist enable row level security;

-- 6. DROP OLD OPEN POLICIES (Security Hardening)
drop policy if exists "Enable all access for works management" on public.works;
drop policy if exists "Enable all access for guestbook management" on public.guestbook;

-- 7. NEW POLICIES

-- WORKS
-- Public Read
create policy "Public works are viewable by everyone"
  on public.works for select
  using ( status = 'published' );

-- Admin Write (Authenticated)
create policy "Admins can manage works"
  on public.works for all
  to authenticated
  using ( true )
  with check ( true );

-- GUESTBOOK
-- Public Insert
create policy "Anyone can sign guestbook"
  on public.guestbook for insert
  with check ( true );

-- Public Read (Approved only)
create policy "Public guestbook entries are viewable by everyone"
  on public.guestbook for select
  using ( is_approved = true );

-- Admin Manage (Authenticated)
create policy "Admins can manage guestbook"
  on public.guestbook for all
  to authenticated
  using ( true )
  with check ( true );

-- PORTAL
-- Public Read
create policy "Public portal items are viewable"
  on public.portal_items for select
  using ( is_visible = true );

-- Admin Manage
create policy "Admins can manage portal"
  on public.portal_items for all
  to authenticated
  using ( true )
  with check ( true );

-- PROFILE
-- Public Read
create policy "Public profile is viewable"
  on public.profile for select
  using ( true );

-- Admin Manage
create policy "Admins can manage profile"
  on public.profile for all
  to authenticated
  using ( true )
  with check ( true );

-- PLAYLIST
-- Public Read
create policy "Public playlist is viewable"
  on public.playlist for select
  using ( true );

-- Admin Manage
create policy "Admins can manage playlist"
  on public.playlist for all
  to authenticated
  using ( true )
  with check ( true );
