-- 1. Create the 'works' table for your portfolio items
create table public.works (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  type text not null check (type in ('ESSAY', 'SKETCH', 'PROJECT', 'MUSIC')),
  date text, -- e.g. "2024.01"
  content_url text, -- optional link to external content
  image_url text -- optional cover image
);

-- 2. Create the 'guestbook' table
create table public.guestbook (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  message text not null,
  visitor_id uuid not null, -- Unique ID stored in user's browser to prevent identity spoofing
  is_approved boolean default false -- Messages are hidden until approved
);

-- 3. Enable Row Level Security (RLS)
alter table public.works enable row level security;
alter table public.guestbook enable row level security;

-- 4. Create Policies (Open for now, but you can restrict writes to authenticated users later)

-- WORKS POLICIES
-- Allow anyone to read works
create policy "Public works are viewable by everyone."
  on public.works for select
  using ( true );

-- Allow Admin (via Anon Key + Client Logic) to modify works
create policy "Enable all access for works management"
  on public.works for all
  using ( true )
  with check ( true );

-- GUESTBOOK POLICIES
-- Allow anyone to insert guestbook entries (Visitors signing)
create policy "Anyone can sign guestbook."
  on public.guestbook for insert
  with check ( true );

-- Allow anyone to read ONLY APPROVED guestbook entries
create policy "Public guestbook entries are viewable by everyone."
  on public.guestbook for select
  using ( is_approved = true );

-- Allow Admin (via Anon Key + Client Logic) to see ALL entries (for moderation) and update/delete
-- Note: This technically overlaps with the select policy above, but for Admin, we need to see unapproved ones.
-- Since the public select policy filters by `is_approved = true`, we need a separate policy for Admin or
-- rely on the fact that RLS is additive. However, `using (true)` overrides specific filters.
create policy "Enable all access for guestbook management"
  on public.guestbook for all
  using ( true )
  with check ( true );
